<?php

namespace Ger\Bundle\HostingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationDatabaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationDatabaseRepository extends EntityRepository
{
}
