<?php

namespace Ger\Bundle\HostingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatabaseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatabaseTypeRepository extends EntityRepository
{
}
