ger_hosting_environment:
    resource: "@GerHostingBundle/Resources/config/routing/environment.yml"

ger_hosting_authority:
    resource: "@GerHostingBundle/Resources/config/routing/authority.yml"

ger_hosting_application:
    resource: "@GerHostingBundle/Resources/config/routing/application.yml"

ger_hosting_databasetype:
    resource: "@GerHostingBundle/Resources/config/routing/database_type.yml"

ger_hosting_cachingtype:
    resource: "@GerHostingBundle/Resources/config/routing/caching_type.yml"

ger_hosting_rabbitmqexchange:
    resource: "@GerHostingBundle/Resources/config/routing/rabbitmq_exchange.yml"

ger_hosting_rabbitmqqueue:
    resource: "@GerHostingBundle/Resources/config/routing/rabbitmq_queue.yml"