ger_hosting_environment:
    resource: "@GerHostingBundle/Resources/config/routing/environment.yml"

ger_hosting_authority:
    resource: "@GerHostingBundle/Resources/config/routing/authority.yml"

ger_hosting_application:
    resource: "@GerHostingBundle/Resources/config/routing/application.yml"