services:
    ger_hosting.form.type.environment:
        class: Ger\Bundle\HostingBundle\Form\Type\EnvironmentType
        tags:
            - { name: form.type, alias: ger_hosting_environment }
    ger_hosting.form.type.authority:
        class: Ger\Bundle\HostingBundle\Form\Type\AuthorityType
        tags:
            - { name: form.type, alias: ger_hosting_authority }
    ger_hosting.form.type.application:
        class: Ger\Bundle\HostingBundle\Form\Type\ApplicationType
        tags:
            - { name: form.type, alias: ger_hosting_application }
    ger_hosting.form.type.application_database:
        class: Ger\Bundle\HostingBundle\Form\Type\ApplicationDatabaseType
        tags:
            - { name: form.type, alias: ger_hosting_application_database }
    ger_hosting.form.type.database_type:
        class: Ger\Bundle\HostingBundle\Form\Type\DatabaseTypeType
        tags:
            - { name: form.type, alias: ger_hosting_databasetype }
    ger_hosting.form.type.application_caching:
        class: Ger\Bundle\HostingBundle\Form\Type\ApplicationCachingType
        tags:
            - { name: form.type, alias: ger_hosting_application_caching }
    ger_hosting.form.type.caching_type:
        class: Ger\Bundle\HostingBundle\Form\Type\CachingTypeType
        tags:
            - { name: form.type, alias: ger_hosting_cachingtype }
    ger_hosting.form.type.application_consume_message:
        class: Ger\Bundle\HostingBundle\Form\Type\ApplicationConsumeMessageType
        tags:
            - { name: form.type, alias: ger_hosting_application_consume_message }
    ger_hosting.form.type.application_produce_message:
        class: Ger\Bundle\HostingBundle\Form\Type\ApplicationProduceMessageType
        tags:
            - { name: form.type, alias: ger_hosting_application_produce_message }
    ger_hosting.form.type.rabbitmq_exchange:
        class: Ger\Bundle\HostingBundle\Form\Type\RabbitMQExchangeType
        tags:
            - { name: form.type, alias: ger_hosting_rabbitmqexchange }
    ger_hosting.form.type.rabbitmq_queue:
        class: Ger\Bundle\HostingBundle\Form\Type\RabbitMQQueueType
        tags:
            - { name: form.type, alias: ger_hosting_rabbitmqqueue }