services:
    ger_hosting.form.type.environment:
        class: Ger\Bundle\HostingBundle\Form\Type\EnvironmentType
        tags:
            - { name: form.type, alias: ger_hosting_environment }
    ger_hosting.form.type.authority:
        class: Ger\Bundle\HostingBundle\Form\Type\AuthorityType
        tags:
            - { name: form.type, alias: ger_hosting_authority }
    ger_hosting.form.type.application:
        class: Ger\Bundle\HostingBundle\Form\Type\ApplicationType
        tags:
            - { name: form.type, alias: ger_hosting_application }